server:
    port: 8778

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:8806/hello?useUnicode=true&characterEncoding=utf8
        username: hello
        password: hello
        driver-class-name: com.mysql.jdbc.Driver
    application:
        name: cloud-ecloud-oauthz
    cloud:
        zookeeper:
            connect-string: "127.0.0.1:2181"
mybatis:
    type-aliases-package: com.cloud.ecloud.oauthz.entity
    mapper-locations:
      - classpath:mapper/*.xml
      - classpath:dao/*.xml
    configuration:
        map-underscore-to-camel-case: false
